// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1NCiguh9SlE4MCBrgRR9UktcGysMDb4s',
    appId: '1:229452606881:web:ba7c6be9f2bf69756c6fe0',
    messagingSenderId: '229452606881',
    projectId: 'myntra-669c0',
    authDomain: 'myntra-669c0.firebaseapp.com',
    storageBucket: 'myntra-669c0.appspot.com',
    measurementId: 'G-WV4R92F1RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTO2paUeFl9ZI9R0ougET4OGWEjZqRwmc',
    appId: '1:229452606881:android:f6158b4c38da097b6c6fe0',
    messagingSenderId: '229452606881',
    projectId: 'myntra-669c0',
    storageBucket: 'myntra-669c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx4M8_vK8hHwDVLQ1AyT74qC93xH59nSM',
    appId: '1:229452606881:ios:8cd443c69c6f33606c6fe0',
    messagingSenderId: '229452606881',
    projectId: 'myntra-669c0',
    storageBucket: 'myntra-669c0.appspot.com',
    iosBundleId: 'com.example.myntra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx4M8_vK8hHwDVLQ1AyT74qC93xH59nSM',
    appId: '1:229452606881:ios:8cd443c69c6f33606c6fe0',
    messagingSenderId: '229452606881',
    projectId: 'myntra-669c0',
    storageBucket: 'myntra-669c0.appspot.com',
    iosBundleId: 'com.example.myntra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1NCiguh9SlE4MCBrgRR9UktcGysMDb4s',
    appId: '1:229452606881:web:7dcb9c6510a8e8ec6c6fe0',
    messagingSenderId: '229452606881',
    projectId: 'myntra-669c0',
    authDomain: 'myntra-669c0.firebaseapp.com',
    storageBucket: 'myntra-669c0.appspot.com',
    measurementId: 'G-16V7TV4WZ6',
  );
}
